providers:
  claude:
    templates_dir: ~/.claude
    mcp_config: ~/.claude.json
  opencode:
    templates_dir: ~/.config/opencode
    mcp_config: ~/.config/opencode/opencode.json
  gemini:
    mcp_config: ~/.gemini/settings.json

mcp_servers:
  vectorcode-mcp-server:
    values:
      command: vectorcode-mcp-server
      args: []
    providers:
      claude:
        enabled: false
      opencode:
        enabled: false
        extra:
          type: local
      gemini:
        enabled: false

  dash-api:
    values:
      command: uvx
      args:
        - --from
        - git+https://github.com/Kapeli/dash-mcp-server.git
        - dash-mcp-server
    providers:
      claude:
        enabled: true
      opencode:
        enabled: true
        extra:
          type: local
      gemini:
        enabled: true
