git:
  pagers:
    - externalDiffCommand: difft --color=always
gui:
  theme:
    inactiveBorderColor:
      - "#666666"
    selectedLineBgColor:
      - "#1e1e1e"
    defaultFgColor:
      - "#aaaaaa"
